# ini file for alembic
# path to migration scripts
script_location = ./database/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)d_%%(created)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
sqlalchemy.url = driver://user:password@localhost/dbname

# The output encoding used when revision files
# are written from script.py.mako. The template
# itself is encoded in UTF-8 as of Alembic 1.3; this parameter affects the encoding of the
# const output .py files
sqlalchemy.encoding = utf-8

# When set to 'true', revision generate new files
# with the initial in the message.
# When 'false', will skip the checks
compare_type = false

# When set to 'true', the presence of foreign keys is
# considered as a reason to generate ALTER statements.
# When set to 'false', foreign keys are not considered
# as reasons to generate ALTER statements.
# Set to false for SQLite
compare_server_default = false
